// @gablura/auth-core — Default configuration and config merge utility

import type { AuthCoreConfig, AuditSeverity, AuditEventType } from "./types.js";

export const DEFAULTS = {
  keyPrefix: "focura:",
  issuer: "focura-app",
  audience: "focura-backend",
  accessTokenExpiry: "15m",
  refreshTokenExpiry: "7d",
  sseTokenExpiry: "30s",
  currentVersion: 1,
  maxConcurrentSessions: 5,
  sessionMetadataTtl: 7 * 24 * 60 * 60,
  lockoutMaxFailures: 10,
  lockoutSeconds: 15 * 60,
  lockoutWindowSeconds: 60 * 60,
  refreshLockTtlSeconds: 45,
  refreshDedupeTtlSeconds: 30,
  revokedSessionTtl: 7 * 24 * 60 * 60,
  inactivityTimeout: 7 * 24 * 60 * 60,
  absoluteTimeout: 7 * 24 * 60 * 60,
  maxSessionAge: 30 * 24 * 60 * 60 * 1000,
} as const;

export function resolveConfig(raw: AuthCoreConfig) {
  return {
    ...raw,
    keyPrefix: raw.keyPrefix ?? DEFAULTS.keyPrefix,
    issuer: raw.jwt.issuer ?? DEFAULTS.issuer,
    audience: raw.jwt.audience ?? DEFAULTS.audience,
    accessTokenExpiry: raw.jwt.accessTokenExpiry ?? DEFAULTS.accessTokenExpiry,
    refreshTokenExpiry: raw.jwt.refreshTokenExpiry ?? DEFAULTS.refreshTokenExpiry,
    sseTokenExpiry: raw.jwt.sseTokenExpiry ?? DEFAULTS.sseTokenExpiry,
    currentVersion: raw.jwt.currentVersion ?? DEFAULTS.currentVersion,
    maxConcurrentSessions: raw.session?.maxConcurrent ?? DEFAULTS.maxConcurrentSessions,
    sessionMetadataTtl: raw.session?.metadataTtl ?? DEFAULTS.sessionMetadataTtl,
    lockoutMaxFailures: raw.lockout?.maxFailures ?? DEFAULTS.lockoutMaxFailures,
    lockoutSeconds: raw.lockout?.lockoutSeconds ?? DEFAULTS.lockoutSeconds,
    lockoutWindowSeconds: raw.lockout?.windowSeconds ?? DEFAULTS.lockoutWindowSeconds,
    inactivityTimeout: raw.session?.inactivityTimeout ?? 7 * 24 * 60 * 60,
    absoluteTimeout: raw.session?.absoluteTimeout ?? 7 * 24 * 60 * 60,
    maxSessionAge: raw.session?.maxSessionAge ?? DEFAULTS.maxSessionAge,
    serverSecret: raw.serverSecret,
    trustedProxies: raw.trustedProxies,
  };
}

export type ResolvedConfig = ReturnType<typeof resolveConfig>;

export const AUDIT_SEVERITY: Record<AuditEventType, AuditSeverity> = {
  LOGIN_SUCCESS: "info",
  LOGIN_FAILED: "warn",
  LOGIN_BLOCKED: "warn",
  LOGOUT: "info",
  LOGOUT_ALL_DEVICES: "info",
  TOKEN_REFRESHED: "info",
  TOKEN_REVOKED: "info",
  TOKEN_EXPIRED: "info",
  TOKEN_VERSION_MISMATCH: "warn",
  TOKEN_REPLAY_DETECTED: "critical",
  EXCHANGE_SUCCESS: "info",
  EXCHANGE_FAILED: "warn",
  SSE_CONNECTED: "info",
  SSE_DISCONNECTED: "info",
  ACCOUNT_LOCKED: "critical",
  TOTP_VERIFIED: "info",
  TOTP_FAILED: "warn",
  PERMISSION_DENIED: "warn",
  EMAIL_NOT_VERIFIED: "warn",
  SESSION_HIJACK_DETECTED: "critical",
  SESSION_BOUND: "info",
  SESSION_REBOUND: "info",
  SESSION_TIMEOUT: "info",
  MAX_SESSIONS_REACHED: "warn",
  SESSION_REVOKED: "info",
  SESSIONS_REVOKED: "info",
  DEVICE_MISMATCH: "warn",
  SUSPICIOUS_IP_CHANGE: "warn",
  CSRF_VALIDATION_FAILED: "warn",
  UNAUTHORIZED_ACCESS: "warn",
  RATE_LIMIT_EXCEEDED: "warn",
  MALWARE_DETECTED: "critical",
  SUSPICIOUS_ACTIVITY: "warn",
  DATA_EXPORT: "info",
  DATA_DELETION: "critical",
  SENSITIVE_DATA_ACCESS: "warn",
  WORKSPACE_CREATED: "info",
  WORKSPACE_DELETED: "critical",
  MEMBER_ADDED: "info",
  MEMBER_REMOVED: "info",
  ROLE_CHANGED: "info",
  SUBSCRIPTION_CREATED: "info",
  SUBSCRIPTION_CANCELLED: "info",
  PAYMENT_FAILED: "warn",
};
